CREATE TABLE BIP.TMP_PMW_BIPS
(
	NUMSEQ NUMBER,
	LIGNEBIPCODE VARCHAR2(4),
	STRUCTUREACTION VARCHAR2(2),
	ETAPENUM NUMBER,
	TACHENUM NUMBER,
	STACHENUM NUMBER,
	CONSODEBDATE DATE,
	CONSOFINDATE DATE,
	RESSBIPCODE NUMBER,
	CONSOQTE NUMBER(8,2)
);

exit;