/*
 * 
 * New table PROFIL_LOCALIZE_LOGS for new invoice calculation PROFIL_LOCALIZE
 * */

  CREATE TABLE PROFIL_LOCALIZE_LOGS 
   (	PROFIL_LOCALIZE VARCHAR2(12) NOT NULL, 
	DATE_EFFET DATE NOT NULL, 
	DATE_LOG DATE NOT NULL, 
	USER_LOG VARCHAR2(30) NOT NULL, 
	COLONNE VARCHAR2(30) NOT NULL, 
	VALEUR_PREC VARCHAR2(300), 
	VALEUR_NOUV VARCHAR2(300), 
	COMMENTAIRE VARCHAR2(200));
	
	
	 ALTER TABLE PROFIL_LOCALIZE_LOGS ADD CONSTRAINT PROFIL_LOCALIZE_LOGS_PK PRIMARY KEY (USER_LOG, PROFIL_LOCALIZE, DATE_LOG, DATE_EFFET, COLONNE);

   COMMENT ON COLUMN PROFIL_LOCALIZE_LOGS.PROFIL_LOCALIZE IS 'Profil de LOCALIZE';
   COMMENT ON COLUMN PROFIL_LOCALIZE_LOGS.DATE_EFFET IS 'Date d''effet au Format AAAA';
   COMMENT ON COLUMN PROFIL_LOCALIZE_LOGS.DATE_LOG IS 'Date du log';
   COMMENT ON COLUMN PROFIL_LOCALIZE_LOGS.USER_LOG IS 'Identifiant utilisateur arpège';
   COMMENT ON COLUMN PROFIL_LOCALIZE_LOGS.COLONNE IS 'Nom de la colonne impactée';
   COMMENT ON COLUMN PROFIL_LOCALIZE_LOGS.VALEUR_PREC IS 'Précédente valeur';
   COMMENT ON COLUMN PROFIL_LOCALIZE_LOGS.VALEUR_NOUV IS 'Nouvelle valeur';
   COMMENT ON COLUMN PROFIL_LOCALIZE_LOGS.COMMENTAIRE IS 'Commentaire';
