/*
 * 
 * New Synonyms in BIPIHM for PROFIL_LOCALIZE
 * */


  CREATE OR REPLACE SYNONYM BIPIHM.PROFIL_LOCALIZE FOR BIP.PROFIL_LOCALIZE;
  CREATE OR REPLACE SYNONYM BIPIHM.PACK_PROFIL_LOCALIZE FOR BIP.PACK_PROFIL_LOCALIZE;
