
/*
 * 
 * New Grants for PROFIL_LOCALIZE to BIPIHM
 * */

GRANT SELECT,UPDATE,INSERT,DELETE ON BIP.PROFIL_LOCALIZE TO BIPIHM;
GRANT EXECUTE ON BIP.PACK_PROFIL_LOCALIZE TO BIPIHM;

GRANT SELECT ON PROFIL_LOCALIZE TO ROLE_DBA_ME;
GRANT SELECT ON PROFIL_LOCALIZE TO ROLE_VISU_ME;
GRANT SELECT ON PROFIL_LOCALIZE TO ROLE_VISU_MO;

GRANT SELECT ON PROFIL_LOCALIZE_LOGS TO ROLE_DBA_ME;
GRANT SELECT ON PROFIL_LOCALIZE_LOGS TO ROLE_VISU_ME;
GRANT SELECT ON PROFIL_LOCALIZE_LOGS TO ROLE_VISU_MO;

GRANT SELECT,INSERT,DELETE ON PROFIL_LOCALIZE TO ROLE_REMOTE;
GRANT ALTER,INDEX,REFERENCES ON PROFIL_LOCALIZE TO BIPIHM;
GRANT SELECT ON PROFIL_LOCALIZE TO BIPH;

GRANT SELECT,INSERT,DELETE ON PROFIL_LOCALIZE_LOGS TO ROLE_REMOTE;
GRANT ALTER,INDEX,REFERENCES ON PROFIL_LOCALIZE_LOGS TO BIPIHM;
GRANT SELECT ON PROFIL_LOCALIZE_LOGS TO BIPH;



