
/*
 * 
 * New TYPE_DOMAINE and History backup for Profile localize tables
 * */

UPDATE TYPE_DOMAINE SET LIB_DOMAINE = 'Expertise' WHERE CODE_DOMAINE = 'CE';
INSERT INTO TYPE_DOMAINE (CODE_DOMAINE,LIB_DOMAINE,FLAGLOCK) VALUES ('CO','Conseil','0');
INSERT INTO LISTE_TABLE_HISTO VALUES ('PROFIL_LOCALIZE');
