 
--New temp tables for CARAT implementation 
CREATE TABLE BIP.TEMP_DMP_PID 
   (	PID VARCHAR2(4 BYTE)
   );
   
   
    CREATE TABLE BIP.TEMP_SSTACHE_RESS 
   (	FACTPID VARCHAR2(4 BYTE), 
	PID VARCHAR2(4 BYTE), 
	ASNOM VARCHAR2(30 BYTE), 
	ECET CHAR(2 BYTE), 
	ACTA CHAR(2 BYTE), 
	ACST CHAR(2 BYTE), 
	AIST CHAR(6 BYTE), 
	TACHEAXEMETIER VARCHAR2(12 BYTE), 
	JANVIER NUMBER(7,2), 
	FEVRIER NUMBER(7,2), 
	MARS NUMBER(7,2), 
	AVRIL NUMBER(7,2), 
	MAI NUMBER(7,2), 
	JUIN NUMBER(7,2), 
	JUILLET NUMBER(7,2), 
	AOUT NUMBER(7,2), 
	SEPTEMBRE NUMBER(7,2), 
	OCTOBRE NUMBER(7,2), 
	NOVEMBRE NUMBER(7,2), 
	DECEMBRE NUMBER(7,2), 
	IDENT NUMBER(5,0), 
	CODSG NUMBER(7,0), 
	SOCCODE CHAR(4 BYTE), 
	NIVEAU VARCHAR2(2 BYTE), 
	COUT NUMBER(12,2), 
	LIBETAPE VARCHAR2(30 BYTE), 
	LIBTACHE VARCHAR2(30 BYTE), 
	DATE_DEB_INI DATE, 
	DATE_FIN_INI DATE, 
	DATE_DEB_REV DATE, 
	DATE_FIN_REV DATE, 
	STATUT_SSTACHE CHAR(2 BYTE), 
	DUREE_SSTACHE NUMBER(5,0), 
	PARAM_SSTACHE VARCHAR2(5 BYTE), 
	CAFI NUMBER(6,0), 
	TYPE_RESSOURCE VARCHAR2(5 BYTE), 
	CODE_PRESTATION CHAR(3 BYTE), 
	MCI VARCHAR2(5 BYTE), 
	CDEB DATE
   ) ;

  CREATE INDEX BIP.IDX1_TEMP_SSTACHE_RESS ON BIP.TEMP_SSTACHE_RESS (PID) ;

  CREATE INDEX BIP.IDX2_TEMP_SSTACHE_RESS ON BIP.TEMP_SSTACHE_RESS (CODSG) ;

  CREATE INDEX BIP.IDX3_TEMP_SSTACHE_RESS ON BIP.TEMP_SSTACHE_RESS (IDENT) ;
  
  CREATE TABLE BIP.TEMP_SSTACHE_RESS_FULL 
   (	FACTPID VARCHAR2(4 BYTE), 
	PID VARCHAR2(4 BYTE), 
	ASNOM VARCHAR2(30 BYTE), 
	ECET CHAR(2 BYTE), 
	ACTA CHAR(2 BYTE), 
	ACST CHAR(2 BYTE), 
	AIST CHAR(6 BYTE), 
	TACHEAXEMETIER VARCHAR2(12 BYTE), 
	JANVIER NUMBER(7,2), 
	FEVRIER NUMBER(7,2), 
	MARS NUMBER(7,2), 
	AVRIL NUMBER(7,2), 
	MAI NUMBER(7,2), 
	JUIN NUMBER(7,2), 
	JUILLET NUMBER(7,2), 
	AOUT NUMBER(7,2), 
	SEPTEMBRE NUMBER(7,2), 
	OCTOBRE NUMBER(7,2), 
	NOVEMBRE NUMBER(7,2), 
	DECEMBRE NUMBER(7,2), 
	IDENT NUMBER(5,0), 
	CODSG NUMBER(7,0), 
	SOCCODE CHAR(4 BYTE), 
	NIVEAU VARCHAR2(2 BYTE), 
	COUT NUMBER(12,2), 
	LIBETAPE VARCHAR2(30 BYTE), 
	LIBTACHE VARCHAR2(30 BYTE), 
	DATE_DEB_INI DATE, 
	DATE_FIN_INI DATE, 
	DATE_DEB_REV DATE, 
	DATE_FIN_REV DATE, 
	STATUT_SSTACHE CHAR(2 BYTE), 
	DUREE_SSTACHE NUMBER(5,0), 
	PARAM_SSTACHE VARCHAR2(5 BYTE), 
	CAFI NUMBER(6,0), 
	TYPE_RESSOURCE VARCHAR2(5 BYTE), 
	CODE_PRESTATION CHAR(3 BYTE), 
	MCI VARCHAR2(5 BYTE), 
	CDEB DATE
   );

  CREATE INDEX BIP.IDX1_TEMP_SSTACHE ON BIP.TEMP_SSTACHE_RESS_FULL (ECET) ;

  CREATE INDEX BIP.IDX2_TEMP_SSTACHE ON BIP.TEMP_SSTACHE_RESS_FULL (PID) ;

  CREATE INDEX BIP.IDX3_TEMP_SSTACHE ON BIP.TEMP_SSTACHE_RESS_FULL (FACTPID) ;

  CREATE INDEX BIP.IDX4_TEMP_SSTACHE ON BIP.TEMP_SSTACHE_RESS_FULL (IDENT) ;

  CREATE INDEX BIP.IDX5_TEMP_SSTACHE ON BIP.TEMP_SSTACHE_RESS_FULL (CODSG) ;

