
create or replace FUNCTION BIP.IS_RBDF_DPG (L_CODSG NUMBER) RETURN VARCHAR2 AS 
L_TMP NUMBER(9) := 0;
BEGIN
  
  SELECT distinct 1 INTO L_TMP FROM CODSG_RBDF WHERE CODSG = L_CODSG;
  RETURN 'Y';
  EXCEPTION
  WHEN NO_DATA_FOUND THEN  
  RETURN 'N';
END IS_RBDF_DPG;
/
