alter table LIGNE_BIP_MAJ_MASSE add (LINEAXISBUSINESS1 VARCHAR2(40),LINEAXISBUSINESS2 VARCHAR2(12));	

COMMENT ON COLUMN BIP.LIGNE_BIP_MAJ_MASSE.LINEAXISBUSINESS1 IS  'axe metier ligne 1';

COMMENT ON COLUMN BIP.LIGNE_BIP_MAJ_MASSE.LINEAXISBUSINESS2 IS  'axe metier ligne 2';
