getimpact EIET >getimpact.log/EIET.log
getimpact AIST >getimpact.log/AIST.log
getimpact AISTTY >getimpact.log/AISTTY.log
getimpact PCLE >getimpact.log/PCLE.log
getimpact PVALID >getimpact.log/PVALID.log
getimpact PTYPE >getimpact.log/PTYPE.log
getimpact FACTPTY >getimpact.log/FACTPTY.log
getimpact PETAT >getimpact.log/PETAT.log
getimpact PNOM >getimpact.log/PNOM.log
getimpact FACTPNO >getimpact.log/FACTPNO.log
getimpact PDSG >getimpact.log/PDSG.log
getimpact PCPI >getimpact.log/PCPI.log
getimpact FACTPCP >getimpact.log/FACTPCP.log
getimpact PCMOUVRA >getimpact.log/PCMOUVRA.log
getimpact FACTPCM >getimpact.log/FACTPCM.log
getimpact PNMOUVRA >getimpact.log/PNMOUVRA.log
getimpact PCACTIVITE >getimpact.log/PCACTIVITE.log
getimpact PDATDEBPRE >getimpact.log/PDATDEBPRE.log
getimpact PDATFINPRE >getimpact.log/PDATFINPRE.log
getimpact RNOM >getimpact.log/RNOM.log
getimpact RPRENOM >getimpact.log/RPRENOM.log
getimpact DATDEP >getimpact.log/DATDEP.log
getimpact DIVSECGROU >getimpact.log/DIVSECGROU.log
getimpact CPIDENT >getimpact.log/CPIDENT.log
getimpact COUT >getimpact.log/COUT.log
getimpact MATRICULE >getimpact.log/MATRICULE.log
getimpact SOCIETE >getimpact.log/SOCIETE.log
getimpact DISPO >getimpact.log/DISPO.log
getimpact CHINIT >getimpact.log/CHINIT.log
getimpact CHRAF >getimpact.log/CHRAF.log
getimpact RTYPE >getimpact.log/RTYPE.log
